apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: wildcard-markdavison-kiwi
spec:
  backendType: vault
  vaultMountPoint: zeno-cluster
  vaultRole: zeno-cluster-role
  kvVersion: 2
  template:
    type: kubernetes.io/tls
  data:
    - key: kv/data/zeno-cluster/cert/wildcard-markdavison-kiwi
      property: crt
      name: tls.crt
    - key: kv/data/zeno-cluster/cert/wildcard-markdavison-kiwi
      property: key
      name: tls.key