apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: zeno-torrent-secret
spec:
  backendType: vault
  vaultMountPoint: zeno-cluster
  vaultRole: zeno-cluster-role
  kvVersion: 2
  data:
    - key: kv/data/zeno-cluster/torrent/api
      property: API_CLIENT_SECRET
      name: API_CLIENT_SECRET
    - key: kv/data/zeno-cluster/torrent/bff
      property: CLIENT_SECRET
      name: CLIENT_SECRET
    - key: kv/data/zeno-cluster/torrent/bff
      property: SESSION_SECRET
      name: SESSION_SECRET
    - key: kv/data/zeno-cluster/torrent/redis
      property: password
      name: REDIS_PASSWORD
    - key: kv/data/zeno-cluster/torrent/postgres
      property: DB_USER
      name: ZENO_TORRENT_DAEMON__DATABASE_USER
    - key: kv/data/zeno-cluster/torrent/postgres
      property: DB_PASSWORD
      name: ZENO_TORRENT_DAEMON__DATABASE_PASSWORD
    - key: kv/data/zeno-cluster/torrent/postgres
      property: DB_NAME
      name: ZENO_TORRENT_DAEMON__DATABASE_NAME