apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.app }}-svc
  labels:
    app: {{ .Values.web.app }}
spec:
  ports:
  - port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
    protocol: TCP
  selector:
    app: {{ .Values.web.app }}