apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.bff.app}}-ingress
  labels:
    app: {{ .Values.bff.app }}
spec:
  rules:
  - host: {{ .Values.bff.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bff.app}}-svc
            port:
              number: {{ .Values.bff.port }}