apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.bff.app}}-ingress
  labels:
    app: {{ .Values.bff.app }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.web.ingress.host }}
      secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.bff.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bff.app}}-svc
            port:
              number: {{ .Values.bff.port }}